org: storyteller
app: serverless
service: serverless-sls

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  tableName: 'blobs-table-${self:provider.stage}'
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "BlobsDynamoDBTable", "Arn" ] }
  environment:
    BLOBS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getBlob:
    handler: wsgi.handler
    events:
      - http:
          method: GET
          path: /blobs/{proxy+}
          integration: lambda
          request:
            passThrough: NEVER
            template:
              application/json: ‘{}’
  createBlob:
    handler: wsgi.handler
    events:
      - http:
          method: POST
          path: /blobs
          integration: lambda
          request:
            passThrough: NEVER
            template:
              application/json: ‘{}’

resources:
  Resources:
    BlobsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: blob_id
            AttributeType: S
        KeySchema:
          - AttributeName: blob_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
